/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface UiIncentiveDataProviderV3ABI extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): UiIncentiveDataProviderV3ABI;
  clone(): UiIncentiveDataProviderV3ABI;
  methods: {
    getFullReservesIncentiveData(
      provider: string,
      user: string
    ): NonPayableTransactionObject<{
      0: [
        string,
        [
          string,
          string,
          [
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string
          ][]
        ],
        [
          string,
          string,
          [
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string
          ][]
        ],
        [
          string,
          string,
          [
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string
          ][]
        ]
      ][];
      1: [
        string,
        [
          string,
          string,
          [string, string, string, string, string, string, string, string][]
        ],
        [
          string,
          string,
          [string, string, string, string, string, string, string, string][]
        ],
        [
          string,
          string,
          [string, string, string, string, string, string, string, string][]
        ]
      ][];
    }>;

    getReservesIncentivesData(
      provider: string
    ): NonPayableTransactionObject<
      [
        string,
        [
          string,
          string,
          [
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string
          ][]
        ],
        [
          string,
          string,
          [
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string
          ][]
        ],
        [
          string,
          string,
          [
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string,
            string
          ][]
        ]
      ][]
    >;

    getUserReservesIncentivesData(
      provider: string,
      user: string
    ): NonPayableTransactionObject<
      [
        string,
        [
          string,
          string,
          [string, string, string, string, string, string, string, string][]
        ],
        [
          string,
          string,
          [string, string, string, string, string, string, string, string][]
        ],
        [
          string,
          string,
          [string, string, string, string, string, string, string, string][]
        ]
      ][]
    >;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
